/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalhorecup;

import modelo.Livro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriella
 */
public class FrameCadastroLivros extends javax.swing.JFrame {   
    private DefaultTableModel modeloTabela;
    private ArrayList<Livro> livros = new ArrayList<>();
    
    public FrameCadastroLivros() {
        initComponents();
        setLocationRelativeTo(this);
        modeloTabela = new DefaultTableModel(new String[]{"Título", "Autor", "Editora", "Ano de Publicação", "Exemplares Disponíveis"}, 0);
        tbLivros.setModel(modeloTabela);
    }
    public void cadastrarLivro(){
        String titulo = tfTitulo.getText();
        String autor = tfAutor.getText();
        String editora = tfEditora.getText();
        String anoPublicacaoStr = tfAnoPublic.getText();
        String exemplaresDisponiveisStr = tfNumExemplares.getText();

    if (titulo.isEmpty() || autor.isEmpty() || editora.isEmpty() || anoPublicacaoStr.isEmpty() || exemplaresDisponiveisStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    int anoPublicacao;
    int exemplaresDisponiveis;

    try {
        exemplaresDisponiveis = Integer.parseInt(exemplaresDisponiveisStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Número de exemplares deve ser um número válido!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        anoPublicacao = Integer.parseInt(anoPublicacaoStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ano de publicação deve ser um número válido!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
        modeloTabela.addRow(new Object[]{titulo, autor, editora, anoPublicacao, exemplaresDisponiveis});
        JOptionPane.showMessageDialog(this, "Livro cadastrado com sucesso!");
            tfTitulo.setText("");
            tfAutor.setText("");
            tfEditora.setText("");
            tfAnoPublic.setText("");
            tfNumExemplares.setText("");

livros.add(new Livro(titulo, autor, editora, anoPublicacao, exemplaresDisponiveis));
    }
    public void voltarPrincipal(){
        FramePrincipal principal = new FramePrincipal();
        principal.setLocationRelativeTo(this);
        principal.setVisible(true);
        this.dispose(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbTituloLivro = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        lbAutor = new javax.swing.JLabel();
        tfAutor = new javax.swing.JTextField();
        lbAnoPublic = new javax.swing.JLabel();
        tfNumExemplares = new javax.swing.JTextField();
        tfAnoPublic = new javax.swing.JFormattedTextField();
        lbNumExemplares = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        lbEditora = new javax.swing.JLabel();
        tfEditora = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLivros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Livros");

        lbTituloLivro.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbTituloLivro.setText("Título:");

        tfTitulo.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        lbAutor.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbAutor.setText("Autor:");

        tfAutor.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        lbAnoPublic.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbAnoPublic.setText("Ano de Publicação:");

        tfNumExemplares.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        tfAnoPublic.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        tfAnoPublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnoPublicActionPerformed(evt);
            }
        });

        lbNumExemplares.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbNumExemplares.setText("Numeros de Exemplares:");

        btCadastrar.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        lbEditora.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        lbEditora.setText("Editora:");

        tfEditora.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N

        tbLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbLivros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(btCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEditora)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbTituloLivro)
                                .addComponent(tfTitulo)
                                .addComponent(tfAnoPublic, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                            .addComponent(lbAnoPublic))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbAutor)
                            .addComponent(lbNumExemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNumExemplares)
                            .addComponent(tfAutor))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTituloLivro)
                    .addComponent(lbAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnoPublic)
                    .addComponent(lbNumExemplares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumExemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnoPublic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbEditora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
       cadastrarLivro();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        voltarPrincipal();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tfAnoPublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnoPublicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnoPublicActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAnoPublic;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbNumExemplares;
    private javax.swing.JLabel lbTituloLivro;
    private javax.swing.JTable tbLivros;
    private javax.swing.JFormattedTextField tfAnoPublic;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfEditora;
    private javax.swing.JTextField tfNumExemplares;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
